### PR TITLE
Add Basic Roadmap to Implementation Status

### PR DESCRIPTION
**Pull request by wilwade**
Problem
=======
Roadmap desired for showing progress and next steps
[link to Pivotal Tracker #177286273 ](https://www.pivotaltracker.com/story/show/177286273 )

Solution
========
Added a simple roadmap

Change summary:
---------------
* Roadmap showing top line work
* Also has a "status" of done (with a Quarterly date) or other status information

### CODE REVIEW

**Comment by enddynayn** [comment]
👍

**Review by aneyzberg — APPROVED** [review]
this looks good to me. Should any of the work for the implementation of the token model be included in the roadmap?

**Review by shannonwells — APPROVED** [review]
I guess you don't want to put Q1 estimates in there?

**Comment by wilwade** [comment]
@aneyzberg I think anything related to that would be in a separate spec.

@shannonwells Correct. Quarterly is as much as detailed as we want for now. Too much is in flux for anything else.

**Pull request merged**
